#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <light_up_icons.h>

int32_t light_up_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm light_up!");

    return 0;
}
